// ============================================================
// FILE: mockData.ts
// PATH: /Users/hoanghavu/myprojects/CookIt!/src/lib/mockData.ts
// PROJECT: CookIt!
// PURPOSE: Centralized mock data for all screens
// ============================================================

import type { User, Recipe, Collection, Category, PantryItem, MealPlanEntry, Comment, ActivityPost } from './types';

// ── Users ──────────────────────────────────────────────────

export const MOCK_CURRENT_USER: User = {
  id: 'user-0',
  name: 'Alex Johnson',
  username: 'alexcooks',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCC2rYzDk03cl2XFv17aeO0ttaVyqNcZdEHOz_pBOphQCgPrNJS3FV7pFq_ih-72ChyxfO1q4DTeoq6RRZrYNlSsRxdleK2LpVZmiopUB2ki1lHggGBiuYrRHJp7KqUwfh69V-ZwqFSGDOg4O0bMKxbVzeF5JlD-angOWTjUm0UnxnketBXnl9HsaKAUPHe07aNwnd8l2hObGKdKEzsk7iM2TMngc5rfGVTUjUmn6Uga36jfmiZF5zHpyiRw4eTOy8oMi-ntr1TLAL',
  bio: 'Home cook & recipe explorer. I love experimenting with seasonal ingredients.',
  badge: 'Home Chef',
  followers: 284,
  following: 103,
  recipesCount: 42,
};

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Maria Chen',
    username: 'mariabakes',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAiM4XY9tWcMnzEPcKcY0T_QlaIxDyGBkGV-rm1UvZH8g1JudJraYwKSbeyf7QF95VwwpyiPpFQ6-j7JTrfSZ7zUeuPxqT1MCJqkdo5UZPlZXgcS7cBo-QcsMAmQz8-qniiEBggc961PQs1Gl1V9fR_HC-Zebm1eJLf0jxR7QuOA7z-20IzqA7Rds_eGbFBS0fCZnV_aefOFa42Rs33fP2zI4uZzZLP1hMZI3ATdgq4HLQay8ZXaHBRbWprWcgkbYEq5WxzAAJTSWYi',
    bio: 'Baking is my therapy',
    badge: 'Baking Expert',
    followers: 1240,
    following: 87,
    recipesCount: 156,
  },
  {
    id: 'user-2',
    name: 'David Wilson',
    username: 'davidgrills',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCrcJdkggMY9psbNJnYduuKEuNRwoS5iLG-aZqMJqO1VqAVXpwfKt92PLwW2r_O6D0AetcRMFKzaQ1VjDK5LhJyP0zJjeadxJn7wJpmNP5qQiWpXwMpqmvZcwh-6xdxv5X4qViTzkQbLSl-mGy6UMReVD9Gbtt27QXGoKxNiLc5FrMYjBWwxBqq_bgNuUsYLcu91eEFDeauVNURvaUgIVAw1WBlZwvaCBVlVRRskNUzLuE_kXcEw3Exr7vdxjXGt-IGZwnOUEZ0hIl',
    bio: 'Weekend BBQ champion. Ask me about my dry rub.',
    badge: 'Grill Master',
    followers: 3500,
    following: 210,
    recipesCount: 89,
  },
  {
    id: 'user-3',
    name: 'Sophie Laurent',
    username: 'sophiecuisine',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKd4kQtnc8bibgiFQ1ZXjj3TyOl3CY8KVHLE1omeX0TfYcDl9GrfnciAQSUdhDrAmcGjeKs6AL6eJmIhj_yLisrjUwnE7l99f1mgdokBELBZBAb6OVClDIi6Rdn7sZRGHuJyJGd7FZmr9GLyLcRpZKzifq5pas_IqieGtyne1GNI8ncxnbL9JpOm0BBoj9XSTGgHZ3qSHrZI0Fg5RlxAuPdVESvmFLP2-DAJBRdkDxlx5rFIe_1Pe_MNcO0UQftaEOsXHmxb2xavjs',
    bio: 'French cuisine meets modern kitchen. Butter is always the answer.',
    badge: 'Culinary Artist',
    followers: 8900,
    following: 342,
    recipesCount: 214,
  },
  {
    id: 'user-4',
    name: 'Raj Patel',
    username: 'rajspices',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD4S58cPNTkS3VfVglw8Z-onJx0yA6aHnhusVyoP8JUgA5e7HxpadlW4dPV4QT3Xyz7o66OCdtvAxSit_4RRZJF1FHhaeX0vH7xFOy-LJu8gBKZbVvqlZGXtbBxQVhjIgiRrSrtU1FO64UoJRoLkBAcqrhXydUehZHVoL48dboSG0Df4qcvxMDQIMbjqrz6yPFA2VGTeGNdbwNYWcCyieC8cQ3E8ZMeHjcuwGDtPmyRbPY0XzscjuJh8q7hGD6H1X14HLaw9jre75h-',
    bio: 'Spice trader turned chef. Every dish tells a story from my grandmother\'s kitchen.',
    badge: 'Spice Guru',
    followers: 5600,
    following: 178,
    recipesCount: 131,
  },
];

// ── Categories ─────────────────────────────────────────────

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Breakfast', icon: 'egg' },
  { id: 'cat-2', name: 'Salad', icon: 'eco' },
  { id: 'cat-3', name: 'Main Course', icon: 'set_meal' },
  { id: 'cat-4', name: 'Dessert', icon: 'cake' },
  { id: 'cat-5', name: 'Beverage', icon: 'local_cafe' },
  { id: 'cat-6', name: 'Snack', icon: 'fastfood' },
  { id: 'cat-7', name: 'Soup', icon: 'soup_kitchen' },
  { id: 'cat-8', name: 'Vegan', icon: 'nutrition' },
];

// ── Recipes ────────────────────────────────────────────────

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'recipe-1',
    title: 'Watermelon Feta Salad',
    description: 'A refreshing summer salad combining sweet watermelon with tangy feta cheese, fresh mint, and a light honey-lime dressing.',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD3898a_rWbr2l3QkMewEOQ0tsPWNVk4LCGUIDvHb3QI_Lr0hPhxIi9RBvavqpqGICT0UlZf1YSjsT8jfpno2ZtJnxKucmtpC-j6nQYPra7klBunCoWzBR4rqgaYj0Xzlo0mMj-RUJk9UEbdZ7GKobH0vCq7M6HVm7gHyAHto3mdmQJM2pkyfWR1rCh8Asq0jDaP5WecCS25Hk0Oznsp1vYnSLFQyg4__Y4wF95Gs_4__QCOhb57i13_WPqbUDBDOHEsN_Mbi2f8iVR',
    category: 'Salad',
    time: '15 mins',
    prepTime: '15 mins',
    servings: 4,
    difficulty: 'Easy',
    rating: 4.8,
    reviewsCount: 128,
    likesCount: 342,
    isFavorite: true,
    isLiked: false,
    author: MOCK_USERS[0],
    ingredients: [
      { name: 'Watermelon', amount: '4', unit: 'cups cubed' },
      { name: 'Feta cheese', amount: '150', unit: 'g crumbled' },
      { name: 'Fresh mint', amount: '1/4', unit: 'cup' },
      { name: 'Lime juice', amount: '2', unit: 'tbsp' },
      { name: 'Honey', amount: '1', unit: 'tbsp' },
      { name: 'Olive oil', amount: '2', unit: 'tbsp' },
    ],
    steps: [
      { order: 1, instruction: 'Cut watermelon into bite-sized cubes and place in a large bowl.', duration: 5 },
      { order: 2, instruction: 'Whisk together lime juice, honey, and olive oil in a small bowl.', duration: 2 },
      { order: 3, instruction: 'Drizzle dressing over watermelon and toss gently.', duration: 1 },
      { order: 4, instruction: 'Top with crumbled feta and fresh mint leaves. Serve immediately.', duration: 2, tip: 'Best served chilled!' },
    ],
    nutrition: { calories: 185, protein: 6, carbs: 24, fat: 8, fiber: 1 },
    tags: ['summer', 'salad', 'vegetarian', 'quick'],
    createdAt: '2024-06-15',
  },
  {
    id: 'recipe-2',
    title: 'Grilled Lemon Chicken',
    description: 'Juicy chicken marinated in lemon, garlic, and fresh herbs, then grilled to perfection.',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3LLpe8dPcvqoAwxUy7iqLnfKqCgDVMlKfpU1-zWuQCDZS7rAM6Njwrq1oC4ddz1D1xzZjBumbHdByFckJBobnmF_1D6Udf6o2LwNQtg17s3YiezVCiTsbK63rEzBeb8eCwm0xgR1czcFVe46bk1s7kSbz09O2iysQsR0xB7PF6nFY6ji98Ivjdvs9v0pR9tl0wWn0MFppZlxRCOrfCw6fyEJZVBKyQHdhtjzZ4EWV62j3FX2XW1DmoTQmlfsp4UMKehrNBZsKmsyf',
    category: 'Main Course',
    time: '30 mins',
    prepTime: '10 mins',
    cookTime: '20 mins',
    servings: 4,
    difficulty: 'Medium',
    rating: 4.6,
    reviewsCount: 89,
    likesCount: 215,
    isFavorite: false,
    isLiked: true,
    author: MOCK_USERS[1],
    ingredients: [
      { name: 'Chicken breasts', amount: '4', unit: 'pieces' },
      { name: 'Lemon', amount: '2', unit: 'whole' },
      { name: 'Garlic', amount: '4', unit: 'cloves' },
      { name: 'Fresh thyme', amount: '2', unit: 'tbsp' },
      { name: 'Olive oil', amount: '3', unit: 'tbsp' },
      { name: 'Salt & pepper', amount: '', unit: 'to taste' },
    ],
    steps: [
      { order: 1, instruction: 'Mix lemon juice, garlic, thyme, and olive oil. Marinate chicken for at least 30 minutes.', duration: 30, tip: 'Longer marination = more flavor' },
      { order: 2, instruction: 'Heat grill to medium-high heat.', duration: 5 },
      { order: 3, instruction: 'Grill chicken 6-7 minutes per side until internal temp reaches 165°F.', duration: 14 },
      { order: 4, instruction: 'Rest 5 minutes before slicing. Serve with grilled lemon halves.', duration: 5 },
    ],
    nutrition: { calories: 310, protein: 42, carbs: 3, fat: 14 },
    tags: ['chicken', 'grilled', 'healthy', 'protein'],
    createdAt: '2024-05-20',
  },
  {
    id: 'recipe-3',
    title: 'Smoked BBQ Ribs',
    description: 'Fall-off-the-bone ribs with a secret dry rub and tangy BBQ glaze. Low and slow is the only way.',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuARrMyiBKop-gIkpcK191B3_g8aEpTBQ844e5CyWC_jK68Blqlis73Tg0pmKDnPC67e0wMUY1kbSp-c7W6M1yVTclHrPJ_wP9UOCzk7W5Ed46cep59Z19V7_R8Zs_SPVHGNBtvfkLbNztO6rBP22KYsU5jyyEjKSS09QvnSURkEHtRMh5V-2afhhqz7wt5S080YBGYa4FuYH-jtXegarnqgWsxlRVlT6c9KXuyrWWUJKwVN8wAZEKS3VprHv5-qNiLCxvuJKxZ3OV8A',
    category: 'Main Course',
    time: '6 hrs',
    prepTime: '15 mins',
    cookTime: '6 hours',
    servings: 6,
    difficulty: 'Hard',
    rating: 4.9,
    reviewsCount: 245,
    likesCount: 892,
    isFavorite: true,
    isLiked: false,
    author: MOCK_USERS[1],
    ingredients: [
      { name: 'Pork ribs', amount: '2', unit: 'racks' },
      { name: 'Brown sugar', amount: '3', unit: 'tbsp' },
      { name: 'Smoked paprika', amount: '2', unit: 'tbsp' },
      { name: 'Garlic powder', amount: '1', unit: 'tbsp' },
      { name: 'Cumin', amount: '1', unit: 'tsp' },
      { name: 'BBQ sauce', amount: '1', unit: 'cup' },
      { name: 'Apple cider vinegar', amount: '2', unit: 'tbsp' },
    ],
    steps: [
      { order: 1, instruction: 'Mix all dry rub ingredients. Apply generously to both sides of ribs. Refrigerate overnight for best results.', duration: 15, tip: 'The overnight rest is worth it!' },
      { order: 2, instruction: 'Set up smoker at 225°F with hickory or applewood chips.', duration: 20 },
      { order: 3, instruction: 'Smoke ribs for 3 hours unwrapped.', duration: 180 },
      { order: 4, instruction: 'Wrap ribs tightly in foil with a splash of apple cider vinegar. Smoke another 2 hours.', duration: 120 },
      { order: 5, instruction: 'Unwrap and brush generously with BBQ sauce. Smoke 1 final hour until glaze caramelizes.', duration: 60 },
      { order: 6, instruction: 'Rest 15 minutes. Slice between bones and serve.', duration: 15 },
    ],
    nutrition: { calories: 680, protein: 52, carbs: 18, fat: 44 },
    tags: ['bbq', 'ribs', 'smoked', 'weekend'],
    createdAt: '2024-04-10',
  },
  {
    id: 'recipe-4',
    title: 'Berry Smoothie Bowl',
    description: 'Thick blended berry base topped with granola, fresh fruit, and a drizzle of honey.',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCSw71LCG4r8d7OSE5aa1NzY15Hj-vBx0hriSCIlmC-H_g1jvN69zejJXYMDqgp12w0GYIIFQcsrbLfEjh4K_RInNHpmPT4zQ66NqH_hcEI8vlQ843_niqPzcLH6HFRDoNbn3RsFD0dm9Ixky0bXfDJhDzzjLpoZuIVaESw-p4wAvdfAdhF1aitMTjRUrQNOD7qkN6VCqldgzzxPZGPmdLNFq-cfSKT_dkpnh4EFWgmX7wg1lX9665Xlt9oMcxQITLR_OswDtr8WGE1',
    category: 'Breakfast',
    time: '12 mins',
    prepTime: '12 mins',
    servings: 2,
    difficulty: 'Easy',
    rating: 4.7,
    reviewsCount: 63,
    likesCount: 178,
    isFavorite: false,
    isLiked: false,
    author: MOCK_USERS[0],
    ingredients: [
      { name: 'Frozen mixed berries', amount: '2', unit: 'cups' },
      { name: 'Frozen banana', amount: '1', unit: 'whole' },
      { name: 'Greek yogurt', amount: '1/2', unit: 'cup' },
      { name: 'Oat milk', amount: '1/4', unit: 'cup' },
      { name: 'Granola', amount: '1/4', unit: 'cup' },
      { name: 'Honey', amount: '1', unit: 'tbsp' },
      { name: 'Fresh strawberries', amount: '4', unit: 'sliced' },
    ],
    steps: [
      { order: 1, instruction: 'Blend frozen berries, banana, Greek yogurt, and oat milk until thick and smooth. Add liquid sparingly — the base should be very thick.', duration: 3, tip: 'Use as little liquid as possible for spoonable consistency' },
      { order: 2, instruction: 'Pour into a bowl and smooth the surface.', duration: 1 },
      { order: 3, instruction: 'Arrange granola, fresh berries, and toppings in rows. Drizzle with honey.', duration: 5 },
    ],
    nutrition: { calories: 285, protein: 9, carbs: 52, fat: 5, fiber: 7 },
    tags: ['breakfast', 'smoothie', 'healthy', 'vegan'],
    createdAt: '2024-07-01',
  },
  {
    id: 'recipe-5',
    title: 'Peach Iced Tea',
    description: 'Homemade iced tea infused with fresh peaches and a hint of ginger.',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCH1OmCqsU6XHfTp4mOKQKaIh835045Kc51x29i9qcOJ49EWkYKFq0V31pUz-ghqlWWnsgXUgt3A_8ZqEtKJ0uiH2ovYlEAPORfE3voKSrQ2yrCthnGhvLcABZW-B0yptCUiUGkV9fwFqzR74nO0C5LTK4HMW7WOdDqVbv4p6Rsr15_ogDz3zdPSlKPqBJjuBOcwvWCB8f5JbvE60xJfByULmtPMrTir0CB3pyRIqo3UJiIXzeKlhppwCHCyawkXKGnPfsvLVyfjySG',
    category: 'Beverage',
    time: '10 mins',
    prepTime: '10 mins',
    servings: 4,
    difficulty: 'Easy',
    rating: 4.5,
    reviewsCount: 41,
    likesCount: 94,
    isFavorite: false,
    isLiked: false,
    author: MOCK_USERS[0],
    ingredients: [
      { name: 'Black tea bags', amount: '4', unit: 'bags' },
      { name: 'Fresh peaches', amount: '2', unit: 'sliced' },
      { name: 'Fresh ginger', amount: '1', unit: 'inch piece' },
      { name: 'Honey', amount: '3', unit: 'tbsp' },
      { name: 'Lemon juice', amount: '2', unit: 'tbsp' },
      { name: 'Cold water', amount: '4', unit: 'cups' },
    ],
    steps: [
      { order: 1, instruction: 'Brew tea bags in 2 cups of hot water for 5 minutes. Remove bags and let cool.', duration: 5 },
      { order: 2, instruction: 'Blend peaches, ginger, and honey into a smooth purée.', duration: 2 },
      { order: 3, instruction: 'Combine tea, peach purée, lemon juice, and remaining cold water. Stir well.', duration: 1 },
      { order: 4, instruction: 'Serve over ice with a peach slice garnish.', duration: 2, tip: 'Make the peach purée ahead and keep in the fridge for up to 3 days' },
    ],
    nutrition: { calories: 65, protein: 0, carbs: 17, fat: 0 },
    tags: ['beverage', 'summer', 'refreshing'],
    createdAt: '2024-07-12',
  },
  {
    id: 'recipe-6',
    title: 'Classic French Onion Soup',
    description: 'Rich caramelized onion broth topped with toasted baguette and a golden Gruyère crust.',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKd4kQtnc8bibgiFQ1ZXjj3TyOl3CY8KVHLE1omeX0TfYcDl9GrfnciAQSUdhDrAmcGjeKs6AL6eJmIhj_yLisrjUwnE7l99f1mgdokBELBZBAb6OVClDIi6Rdn7sZRGHuJyJGd7FZmr9GLyLcRpZKzifq5pas_IqieGtyne1GNI8ncxnbL9JpOm0BBoj9XSTGgHZ3qSHrZI0Fg5RlxAuPdVESvmFLP2-DAJBRdkDxlx5rFIe_1Pe_MNcO0UQftaEOsXHmxb2xavjs',
    category: 'Soup',
    time: '1.5 hrs',
    prepTime: '15 mins',
    cookTime: '75 mins',
    servings: 4,
    difficulty: 'Medium',
    rating: 4.9,
    reviewsCount: 312,
    likesCount: 1100,
    isFavorite: true,
    isLiked: true,
    author: MOCK_USERS[2],
    ingredients: [
      { name: 'Yellow onions', amount: '6', unit: 'large, thinly sliced' },
      { name: 'Butter', amount: '4', unit: 'tbsp' },
      { name: 'Dry white wine', amount: '1/2', unit: 'cup' },
      { name: 'Beef broth', amount: '6', unit: 'cups' },
      { name: 'Fresh thyme', amount: '4', unit: 'sprigs' },
      { name: 'Baguette', amount: '8', unit: 'slices' },
      { name: 'Gruyère cheese', amount: '200', unit: 'g grated' },
    ],
    steps: [
      { order: 1, instruction: 'Melt butter in a heavy pot over medium heat. Add onions and cook, stirring occasionally, for 45 minutes until deeply caramelized.', duration: 45, tip: 'Patience is key — do not rush the caramelization' },
      { order: 2, instruction: 'Add wine and cook until evaporated, about 3 minutes.', duration: 3 },
      { order: 3, instruction: 'Add broth and thyme. Simmer for 20 minutes. Season with salt and pepper.', duration: 20 },
      { order: 4, instruction: 'Ladle soup into oven-safe bowls. Top with baguette slices and pile on Gruyère.', duration: 5 },
      { order: 5, instruction: 'Broil 2-3 minutes until cheese is bubbly and golden. Serve immediately.', duration: 3 },
    ],
    nutrition: { calories: 420, protein: 18, carbs: 38, fat: 22, fiber: 3 },
    tags: ['french', 'soup', 'comfort food', 'winter'],
    createdAt: '2024-03-05',
  },
  {
    id: 'recipe-7',
    title: 'Mango Lassi',
    description: 'Creamy Indian yogurt drink blended with ripe Alphonso mangoes, cardamom, and a pinch of saffron.',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUPSuMT_RlbYT2j4JUwcfSttElMHvPNaYQ8MLAw0wUjkUu6mQRSLgRkIA_dHmpb9e0xBPN3CrN0IWk2EPo7fd-2_xv7MNlRcAMhVAepO42L4UtEkb37v8b7uibYcUByoslpLydsY0pIFUYEkumnCGJ0zkX1xHKSi_MbElT6xSgFtEN2XDFKQx6oezkG7X8KekW-DuieP8nz7_2cuFRMAVDiKWIYkv_B80cgjp1WOMBrZ11HUnwB5oVO5b8PnvfaXD84r65PQt2C1xt',
    category: 'Beverage',
    time: '8 mins',
    prepTime: '8 mins',
    servings: 2,
    difficulty: 'Easy',
    rating: 4.8,
    reviewsCount: 77,
    likesCount: 203,
    isFavorite: false,
    isLiked: false,
    author: MOCK_USERS[3],
    ingredients: [
      { name: 'Ripe mango', amount: '2', unit: 'cups cubed' },
      { name: 'Plain yogurt', amount: '1', unit: 'cup' },
      { name: 'Milk', amount: '1/2', unit: 'cup' },
      { name: 'Sugar', amount: '2', unit: 'tbsp' },
      { name: 'Cardamom powder', amount: '1/4', unit: 'tsp' },
      { name: 'Saffron', amount: 'a pinch', unit: '' },
    ],
    steps: [
      { order: 1, instruction: 'Soak saffron in 1 tbsp warm milk for 5 minutes.', duration: 5 },
      { order: 2, instruction: 'Blend mango, yogurt, milk, sugar, and cardamom until completely smooth.', duration: 2 },
      { order: 3, instruction: 'Add saffron milk and blend for 10 more seconds. Pour into glasses over ice.', duration: 1, tip: 'Alphonso mangoes give the best flavor, but Ataulfo works too' },
    ],
    nutrition: { calories: 215, protein: 7, carbs: 42, fat: 3 },
    tags: ['indian', 'beverage', 'mango', 'yogurt'],
    createdAt: '2024-06-28',
  },
  {
    id: 'recipe-8',
    title: 'Shakshuka',
    description: 'Eggs poached in a spiced tomato-pepper sauce. A North African breakfast that\'s equally perfect for dinner.',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD4S58cPNTkS3VfVglw8Z-onJx0yA6aHnhusVyoP8JUgA5e7HxpadlW4dPV4QT3Xyz7o66OCdtvAxSit_4RRZJF1FHhaeX0vH7xFOy-LJu8gBKZbVvqlZGXtbBxQVhjIgiRrSrtU1FO64UoJRoLkBAcqrhXydUehZHVoL48dboSG0Df4qcvxMDQIMbjqrz6yPFA2VGTeGNdbwNYWcCyieC8cQ3E8ZMeHjcuwGDtPmyRbPY0XzscjuJh8q7hGD6H1X14HLaw9jre75h-',
    category: 'Breakfast',
    time: '25 mins',
    prepTime: '5 mins',
    cookTime: '20 mins',
    servings: 3,
    difficulty: 'Easy',
    rating: 4.7,
    reviewsCount: 98,
    likesCount: 445,
    isFavorite: false,
    isLiked: false,
    author: MOCK_USERS[3],
    ingredients: [
      { name: 'Eggs', amount: '6', unit: 'large' },
      { name: 'Canned tomatoes', amount: '400', unit: 'g crushed' },
      { name: 'Red bell pepper', amount: '1', unit: 'diced' },
      { name: 'Onion', amount: '1', unit: 'medium, diced' },
      { name: 'Garlic', amount: '3', unit: 'cloves' },
      { name: 'Cumin', amount: '1', unit: 'tsp' },
      { name: 'Smoked paprika', amount: '1', unit: 'tsp' },
      { name: 'Feta cheese', amount: '50', unit: 'g' },
      { name: 'Fresh parsley', amount: '', unit: 'to garnish' },
    ],
    steps: [
      { order: 1, instruction: 'Sauté onion and pepper in olive oil for 5 minutes. Add garlic and spices, cook 1 minute.', duration: 6 },
      { order: 2, instruction: 'Add crushed tomatoes. Simmer 10 minutes until sauce thickens. Season well.', duration: 10, tip: 'Taste the sauce — it should be bold and well-seasoned before adding eggs' },
      { order: 3, instruction: 'Make 6 wells in the sauce and crack an egg into each. Cover and cook 5-7 minutes until whites are set but yolks still runny.', duration: 7 },
      { order: 4, instruction: 'Crumble feta on top and garnish with fresh parsley. Serve with crusty bread.', duration: 1 },
    ],
    nutrition: { calories: 290, protein: 18, carbs: 16, fat: 17, fiber: 4 },
    tags: ['breakfast', 'eggs', 'mediterranean', 'vegetarian'],
    createdAt: '2024-05-03',
  },
  {
    id: 'recipe-9',
    title: 'Chocolate Lava Cake',
    description: 'Individual molten chocolate cakes with a warm, flowing center. Restaurant quality in under 20 minutes.',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCSw71LCG4r8d7OSE5aa1NzY15Hj-vBx0hriSCIlmC-H_g1jvN69zejJXYMDqgp12w0GYIIFQcsrbLfEjh4K_RInNHpmPT4zQ66NqH_hcEI8vlQ843_niqPzcLH6HFRDoNbn3RsFD0dm9Ixky0bXfDJhDzzjLpoZuIVaESw-p4wAvdfAdhF1aitMTjRUrQNOD7qkN6VCqldgzzxPZGPmdLNFq-cfSKT_dkpnh4EFWgmX7wg1lX9665Xlt9oMcxQITLR_OswDtr8WGE1',
    category: 'Dessert',
    time: '20 mins',
    prepTime: '10 mins',
    cookTime: '10 mins',
    servings: 4,
    difficulty: 'Medium',
    rating: 4.9,
    reviewsCount: 187,
    likesCount: 756,
    isFavorite: true,
    isLiked: false,
    author: MOCK_USERS[2],
    ingredients: [
      { name: 'Dark chocolate (70%)', amount: '200', unit: 'g' },
      { name: 'Butter', amount: '100', unit: 'g' },
      { name: 'Eggs', amount: '4', unit: 'whole' },
      { name: 'Egg yolks', amount: '4', unit: 'extra' },
      { name: 'Icing sugar', amount: '150', unit: 'g' },
      { name: 'Plain flour', amount: '50', unit: 'g' },
      { name: 'Cocoa powder', amount: '1', unit: 'tbsp (for dusting)' },
    ],
    steps: [
      { order: 1, instruction: 'Preheat oven to 200°C. Butter and dust 4 ramekins with cocoa.', duration: 5 },
      { order: 2, instruction: 'Melt chocolate and butter together. Let cool slightly.', duration: 5, tip: 'Do not let the chocolate get too hot or it will seize' },
      { order: 3, instruction: 'Whisk eggs, yolks, and sugar until pale and thick. Fold in chocolate mixture and flour.', duration: 3 },
      { order: 4, instruction: 'Fill ramekins 3/4 full. Bake exactly 10-12 minutes — the edges should be set, center still wobbly.', duration: 12, tip: 'Underbaking slightly is better than overbaking!' },
      { order: 5, instruction: 'Run a knife around the edge, invert onto a plate. Serve immediately with ice cream.', duration: 2 },
    ],
    nutrition: { calories: 540, protein: 10, carbs: 48, fat: 34 },
    tags: ['dessert', 'chocolate', 'date night', 'baking'],
    createdAt: '2024-02-14',
  },
  {
    id: 'recipe-10',
    title: 'Butter Chicken (Murgh Makhani)',
    description: 'The iconic creamy tomato-based Indian curry that converted the whole world to Indian food.',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAiM4XY9tWcMnzEPcKcY0T_QlaIxDyGBkGV-rm1UvZH8g1JudJraYwKSbeyf7QF95VwwpyiPpFQ6-j7JTrfSZ7zUeuPxqT1MCJqkdo5UZPlZXgcS7cBo-QcsMAmQz8-qniiEBggc961PQs1Gl1V9fR_HC-Zebm1eJLf0jxR7QuOA7z-20IzqA7Rds_eGbFBS0fCZnV_aefOFa42Rs33fP2zI4uZzZLP1hMZI3ATdgq4HLQay8ZXaHBRbWprWcgkbYEq5WxzAAJTSWYi',
    category: 'Main Course',
    time: '45 mins',
    prepTime: '15 mins',
    cookTime: '30 mins',
    servings: 4,
    difficulty: 'Medium',
    rating: 4.8,
    reviewsCount: 423,
    likesCount: 1890,
    isFavorite: false,
    isLiked: true,
    author: MOCK_USERS[3],
    ingredients: [
      { name: 'Chicken thighs', amount: '700', unit: 'g boneless' },
      { name: 'Plain yogurt', amount: '1/2', unit: 'cup' },
      { name: 'Garam masala', amount: '2', unit: 'tsp' },
      { name: 'Butter', amount: '3', unit: 'tbsp' },
      { name: 'Crushed tomatoes', amount: '400', unit: 'g' },
      { name: 'Heavy cream', amount: '1/2', unit: 'cup' },
      { name: 'Garlic-ginger paste', amount: '2', unit: 'tbsp' },
      { name: 'Fenugreek leaves (kasuri methi)', amount: '1', unit: 'tsp' },
    ],
    steps: [
      { order: 1, instruction: 'Marinate chicken in yogurt and spices for at least 2 hours. Grill or pan-sear until charred.', duration: 120, tip: 'The char marks add a crucial smoky depth to the final dish' },
      { order: 2, instruction: 'Sauté garlic-ginger paste in butter. Add tomatoes and cook down for 15 minutes.', duration: 15 },
      { order: 3, instruction: 'Blend sauce until smooth. Return to pan, add cream and kasuri methi.', duration: 5 },
      { order: 4, instruction: 'Add grilled chicken pieces. Simmer 10 minutes. Adjust seasoning and serve with naan.', duration: 10 },
    ],
    nutrition: { calories: 480, protein: 38, carbs: 12, fat: 30, fiber: 2 },
    tags: ['indian', 'curry', 'chicken', 'comfort food'],
    createdAt: '2024-01-18',
  },
  {
    id: 'recipe-11',
    title: 'Avocado Toast with Poached Egg',
    description: 'The brunch classic, done right: smashed avocado on sourdough with a perfectly poached egg and chili flakes.',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCrcJdkggMY9psbNJnYduuKEuNRwoS5iLG-aZqMJqO1VqAVXpwfKt92PLwW2r_O6D0AetcRMFKzaQ1VjDK5LhJyP0zJjeadxJn7wJpmNP5qQiWpXwMpqmvZcwh-6xdxv5X4qViTzkQbLSl-mGy6UMReVD9Gbtt27QXGoKxNiLc5FrMYjBWwxBqq_bgNuUsYLcu91eEFDeauVNURvaUgIVAw1WBlZwvaCBVlVRRskNUzLuE_kXcEw3Exr7vdxjXGt-IGZwnOUEZ0hIl',
    category: 'Breakfast',
    time: '12 mins',
    prepTime: '5 mins',
    cookTime: '7 mins',
    servings: 1,
    difficulty: 'Easy',
    rating: 4.5,
    reviewsCount: 55,
    likesCount: 312,
    isFavorite: false,
    isLiked: false,
    author: MOCK_USERS[0],
    ingredients: [
      { name: 'Sourdough bread', amount: '2', unit: 'slices' },
      { name: 'Ripe avocado', amount: '1', unit: 'whole' },
      { name: 'Eggs', amount: '2', unit: 'large' },
      { name: 'White vinegar', amount: '1', unit: 'tsp (for poaching)' },
      { name: 'Lemon juice', amount: '1', unit: 'tsp' },
      { name: 'Chili flakes', amount: '', unit: 'to taste' },
      { name: 'Everything bagel seasoning', amount: '', unit: 'optional' },
    ],
    steps: [
      { order: 1, instruction: 'Toast sourdough until golden and crispy.', duration: 3 },
      { order: 2, instruction: 'Smash avocado with lemon juice, salt and pepper. Spread thickly on toast.', duration: 2, tip: 'Leave it slightly chunky for better texture' },
      { order: 3, instruction: 'Bring a pot of water to a gentle simmer with vinegar. Create a swirl and slip eggs in. Poach 3-4 minutes for a runny yolk.', duration: 4 },
      { order: 4, instruction: 'Place poached eggs on top. Season with chili flakes and bagel seasoning.', duration: 1 },
    ],
    nutrition: { calories: 420, protein: 16, carbs: 32, fat: 26, fiber: 8 },
    tags: ['breakfast', 'brunch', 'avocado', 'eggs', 'quick'],
    createdAt: '2024-08-02',
  },
  {
    id: 'recipe-12',
    title: 'Chickpea & Spinach Curry',
    description: 'A hearty vegan curry packed with protein-rich chickpeas, wilted spinach, and warm spices.',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUPSuMT_RlbYT2j4JUwcfSttElMHvPNaYQ8MLAw0wUjkUu6mQRSLgRkIA_dHmpb9e0xBPN3CrN0IWk2EPo7fd-2_xv7MNlRcAMhVAepO42L4UtEkb37v8b7uibYcUByoslpLydsY0pIFUYEkumnCGJ0zkX1xHKSi_MbElT6xSgFtEN2XDFKQx6oezkG7X8KekW-DuieP8nz7_2cuFRMAVDiKWIYkv_B80cgjp1WOMBrZ11HUnwB5oVO5b8PnvfaXD84r65PQt2C1xt',
    category: 'Vegan',
    time: '35 mins',
    prepTime: '10 mins',
    cookTime: '25 mins',
    servings: 4,
    difficulty: 'Easy',
    rating: 4.6,
    reviewsCount: 72,
    likesCount: 389,
    isFavorite: false,
    isLiked: false,
    author: MOCK_USERS[3],
    ingredients: [
      { name: 'Canned chickpeas', amount: '800', unit: 'g drained' },
      { name: 'Baby spinach', amount: '200', unit: 'g' },
      { name: 'Canned tomatoes', amount: '400', unit: 'g' },
      { name: 'Coconut milk', amount: '200', unit: 'ml' },
      { name: 'Onion', amount: '1', unit: 'large' },
      { name: 'Garlic', amount: '4', unit: 'cloves' },
      { name: 'Turmeric', amount: '1', unit: 'tsp' },
      { name: 'Garam masala', amount: '2', unit: 'tsp' },
    ],
    steps: [
      { order: 1, instruction: 'Sauté onion and garlic in oil for 5 minutes. Add spices and cook 1 minute.', duration: 6 },
      { order: 2, instruction: 'Add tomatoes and chickpeas. Simmer 15 minutes until thickened.', duration: 15 },
      { order: 3, instruction: 'Stir in coconut milk and spinach. Cook until spinach wilts, about 3 minutes.', duration: 3, tip: 'Add spinach in batches so it wilts evenly' },
      { order: 4, instruction: 'Season generously. Serve with basmati rice or naan.', duration: 1 },
    ],
    nutrition: { calories: 340, protein: 14, carbs: 46, fat: 10, fiber: 12 },
    tags: ['vegan', 'curry', 'chickpea', 'healthy', 'meal-prep'],
    createdAt: '2024-04-22',
  },
];

// ── Comments ────────────────────────────────────────────────

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'comment-1',
    author: MOCK_USERS[1],
    content: 'Made this last Sunday and it was absolutely incredible. The caramelized onions took 50 minutes but 100% worth it!',
    likesCount: 24,
    createdAt: '2024-06-20',
  },
  {
    id: 'comment-2',
    author: MOCK_USERS[2],
    content: 'Pro tip: add a splash of cognac after the wine burns off. Takes it to another level entirely.',
    likesCount: 41,
    createdAt: '2024-06-18',
  },
  {
    id: 'comment-3',
    author: MOCK_USERS[0],
    content: 'My first time making this and I nailed it! The dry rub formula is perfect. Already have requests to make it again next weekend.',
    likesCount: 17,
    createdAt: '2024-05-12',
  },
  {
    id: 'comment-4',
    author: MOCK_USERS[3],
    content: 'Added kasuri methi at the end like you suggested — that secret ingredient really does make a difference.',
    likesCount: 33,
    createdAt: '2024-02-01',
  },
];

// ── Collections ────────────────────────────────────────────

export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: 'col-1',
    title: 'Summer Favorites',
    description: 'A curated collection of refreshing meals and drinks for the sunny season.',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUPSuMT_RlbYT2j4JUwcfSttElMHvPNaYQ8MLAw0wUjkUu6mQRSLgRkIA_dHmpb9e0xBPN3CrN0IWk2EPo7fd-2_xv7MNlRcAMhVAepO42L4UtEkb37v8b7uibYcUByoslpLydsY0pIFUYEkumnCGJ0zkX1xHKSi_MbElT6xSgFtEN2XDFKQx6oezkG7X8KekW-DuieP8nz7_2cuFRMAVDiKWIYkv_B80cgjp1WOMBrZ11HUnwB5oVO5b8PnvfaXD84r65PQt2C1xt',
    recipesCount: 6,
    type: 'Personal',
    recipes: [MOCK_RECIPES[0], MOCK_RECIPES[3], MOCK_RECIPES[4], MOCK_RECIPES[6], MOCK_RECIPES[7], MOCK_RECIPES[10]],
  },
  {
    id: 'col-2',
    title: 'Quick Weeknight Meals',
    description: 'Ready in under 30 minutes. Because weeknights are hectic.',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3LLpe8dPcvqoAwxUy7iqLnfKqCgDVMlKfpU1-zWuQCDZS7rAM6Njwrq1oC4ddz1D1xzZjBumbHdByFckJBobnmF_1D6Udf6o2LwNQtg17s3YiezVCiTsbK63rEzBeb8eCwm0xgR1czcFVe46bk1s7kSbz09O2iysQsR0xB7PF6nFY6ji98Ivjdvs9v0pR9tl0wWn0MFppZlxRCOrfCw6fyEJZVBKyQHdhtjzZ4EWV62j3FX2XW1DmoTQmlfsp4UMKehrNBZsKmsyf',
    recipesCount: 5,
    type: 'Personal',
    recipes: [MOCK_RECIPES[0], MOCK_RECIPES[1], MOCK_RECIPES[7], MOCK_RECIPES[10], MOCK_RECIPES[11]],
  },
  {
    id: 'col-3',
    title: 'Date Night Specials',
    description: 'Impressive recipes that look hard but aren\'t. Your secret weapon for a perfect evening.',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuARrMyiBKop-gIkpcK191B3_g8aEpTBQ844e5CyWC_jK68Blqlis73Tg0pmKDnPC67e0wMUY1kbSp-c7W6M1yVTclHrPJ_wP9UOCzk7W5Ed46cep59Z19V7_R8Zs_SPVHGNBtvfkLbNztO6rBP22KYsU5jyyEjKSS09QvnSURkEHtRMh5V-2afhhqz7wt5S080YBGYa4FuYH-jtXegarnqgWsxlRVlT6c9KXuyrWWUJKwVN8wAZEKS3VprHv5-qNiLCxvuJKxZ3OV8A',
    recipesCount: 3,
    type: 'Personal',
    recipes: [MOCK_RECIPES[5], MOCK_RECIPES[8], MOCK_RECIPES[1]],
  },
];

// ── Pantry Items ───────────────────────────────────────────

export const MOCK_PANTRY_ITEMS: PantryItem[] = [
  {
    id: 'pantry-1',
    name: 'Basmati Rice',
    quantity: '2.5 kg left',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUBCyeraeUUlEW4SMEsN-_A9VNrV1rAD2m7mXFHBMIbkZooRicyrYem6-6zRQGzTOqjTDI0evhe7DkJGd3RsD1TwYjaLaPAfS3PG2WYUPsMrztc5DpS3ix2MpU6VqUjReJXZ-paXiDNsn9y_VCYvz3HZfgMmhudNqWP8uISKSwHATMQjsbsI6nwVgIRVHnptVCihHFZjWujQrEa17Q1TFjpDZAdEQ37nSIyVqt3wpyJHvXPddoizDBW4_UYGYnum8qmKeKaVf1PhDN',
    imageAlt: 'Close up of uncooked white rice grains',
    levelWidth: '80%',
    category: 'Grains',
  },
  {
    id: 'pantry-2',
    name: 'Rolled Oats',
    quantity: '0.2 kg left',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAuwAWl79ws80HyIpw7BvHMxrWVf2cDIdWs2jGMp-i0XxckVL01zFiLtu2vwSenaGcmCOkXsmbH7BRsDIkRhO_XpwXKnbbRTh75cs3_PlXd6Zj4NQqERPQuWm4g-MWXBgO03IMN62pjk1Ku7w7fYoz4shYhVgsW5dtUj9nPnxU2XHqs1ouHIHvRd-rigtYM8woL7hI_alQJ56IVMYqhB1_69HKuY6O1N_IFIAn-wkXDYe32iLW0jdWistZV0Lm8RE01iya0KrA6p0wr',
    imageAlt: 'Organic rolled oats in a jar',
    levelColor: 'red',
    levelWidth: '10%',
    actionIcon: 'shopping_cart',
    category: 'Grains',
    expiresAt: '2024-08-15',
  },
  {
    id: 'pantry-3',
    name: 'Olive Oil',
    quantity: '500 ml left',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD3898a_rWbr2l3QkMewEOQ0tsPWNVk4LCGUIDvHb3QI_Lr0hPhxIi9RBvavqpqGICT0UlZf1YSjsT8jfpno2ZtJnxKucmtpC-j6nQYPra7klBunCoWzBR4rqgaYj0Xzlo0mMj-RUJk9UEbdZ7GKobH0vCq7M6HVm7gHyAHto3mdmQJM2pkyfWR1rCh8Asq0jDaP5WecCS25Hk0Oznsp1vYnSLFQyg4__Y4wF95Gs_4__QCOhb57i13_WPqbUDBDOHEsN_Mbi2f8iVR',
    imageAlt: 'Bottle of extra virgin olive oil',
    levelWidth: '55%',
    levelColor: 'yellow',
    category: 'Oils & Fats',
  },
  {
    id: 'pantry-4',
    name: 'Smoked Paprika',
    quantity: '45 g left',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUPSuMT_RlbYT2j4JUwcfSttElMHvPNaYQ8MLAw0wUjkUu6mQRSLgRkIA_dHmpb9e0xBPN3CrN0IWk2EPo7fd-2_xv7MNlRcAMhVAepO42L4UtEkb37v8b7uibYcUByoslpLydsY0pIFUYEkumnCGJ0zkX1xHKSi_MbElT6xSgFtEN2XDFKQx6oezkG7X8KekW-DuieP8nz7_2cuFRMAVDiKWIYkv_B80cgjp1WOMBrZ11HUnwB5oVO5b8PnvfaXD84r65PQt2C1xt',
    imageAlt: 'Jar of smoked paprika spice',
    levelWidth: '30%',
    levelColor: 'red',
    actionIcon: 'shopping_cart',
    category: 'Spices',
    expiresAt: '2025-01-10',
  },
  {
    id: 'pantry-5',
    name: 'Canned Chickpeas',
    quantity: '3 cans',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3LLpe8dPcvqoAwxUy7iqLnfKqCgDVMlKfpU1-zWuQCDZS7rAM6Njwrq1oC4ddz1D1xzZjBumbHdByFckJBobnmF_1D6Udf6o2LwNQtg17s3YiezVCiTsbK63rEzBeb8eCwm0xgR1czcFVe46bk1s7kSbz09O2iysQsR0xB7PF6nFY6ji98Ivjdvs9v0pR9tl0wWn0MFppZlxRCOrfCw6fyEJZVBKyQHdhtjzZ4EWV62j3FX2XW1DmoTQmlfsp4UMKehrNBZsKmsyf',
    imageAlt: 'Canned chickpeas',
    levelWidth: '90%',
    levelColor: 'green',
    category: 'Canned',
  },
  {
    id: 'pantry-6',
    name: 'Whole Milk',
    quantity: '0.8 L left',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCH1OmCqsU6XHfTp4mOKQKaIh835045Kc51x29i9qcOJ49EWkYKFq0V31pUz-ghqlWWnsgXUgt3A_8ZqEtKJ0uiH2ovYlEAPORfE3voKSrQ2yrCthnGhvLcABZW-B0yptCUiUGkV9fwFqzR74nO0C5LTK4HMW7WOdDqVbv4p6Rsr15_ogDz3zdPSlKPqBJjuBOcwvWCB8f5JbvE60xJfByULmtPMrTir0CB3pyRIqo3UJiIXzeKlhppwCHCyawkXKGnPfsvLVyfjySG',
    imageAlt: 'Carton of whole milk',
    levelWidth: '40%',
    levelColor: 'yellow',
    category: 'Dairy',
    expiresAt: '2024-08-20',
  },
  {
    id: 'pantry-7',
    name: 'Garam Masala',
    quantity: '80 g left',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD4S58cPNTkS3VfVglw8Z-onJx0yA6aHnhusVyoP8JUgA5e7HxpadlW4dPV4QT3Xyz7o66OCdtvAxSit_4RRZJF1FHhaeX0vH7xFOy-LJu8gBKZbVvqlZGXtbBxQVhjIgiRrSrtU1FO64UoJRoLkBAcqrhXydUehZHVoL48dboSG0Df4qcvxMDQIMbjqrz6yPFA2VGTeGNdbwNYWcCyieC8cQ3E8ZMeHjcuwGDtPmyRbPY0XzscjuJh8q7hGD6H1X14HLaw9jre75h-',
    imageAlt: 'Spice blend garam masala',
    levelWidth: '65%',
    levelColor: 'green',
    category: 'Spices',
  },
  {
    id: 'pantry-8',
    name: 'Dark Chocolate (70%)',
    quantity: '100 g left',
    imageSrc: 'https://lh3.googleusercontent.com/aida-public/AB6AXuARrMyiBKop-gIkpcK191B3_g8aEpTBQ844e5CyWC_jK68Blqlis73Tg0pmKDnPC67e0wMUY1kbSp-c7W6M1yVTclHrPJ_wP9UOCzk7W5Ed46cep59Z19V7_R8Zs_SPVHGNBtvfkLbNztO6rBP22KYsU5jyyEjKSS09QvnSURkEHtRMh5V-2afhhqz7wt5S080YBGYa4FuYH-jtXegarnqgWsxlRVlT6c9KXuyrWWUJKwVN8wAZEKS3VprHv5-qNiLCxvuJKxZ3OV8A',
    imageAlt: 'Bar of dark chocolate',
    levelWidth: '20%',
    levelColor: 'red',
    actionIcon: 'shopping_cart',
    category: 'Baking',
    expiresAt: '2025-03-01',
  },
];

// ── Meal Plan ──────────────────────────────────────────────

export const MOCK_MEAL_PLAN: MealPlanEntry[] = [
  { id: 'mp-1', recipe: MOCK_RECIPES[3], date: '2024-10-07', mealType: 'Breakfast' },
  { id: 'mp-2', recipe: MOCK_RECIPES[0], date: '2024-10-07', mealType: 'Lunch' },
  { id: 'mp-3', recipe: MOCK_RECIPES[1], date: '2024-10-07', mealType: 'Dinner' },
  { id: 'mp-4', recipe: MOCK_RECIPES[10], date: '2024-10-08', mealType: 'Breakfast' },
  { id: 'mp-5', recipe: MOCK_RECIPES[11], date: '2024-10-08', mealType: 'Lunch' },
  { id: 'mp-6', recipe: MOCK_RECIPES[9], date: '2024-10-08', mealType: 'Dinner' },
];

// ── Activity Posts ─────────────────────────────────────────

export const MOCK_ACTIVITY_POSTS: ActivityPost[] = [
  {
    id: 'post-1',
    author: MOCK_USERS[0],
    content: 'Just finished baking this! The crust is super flaky. Used my grandmother\'s secret technique for the glaze. #baking #summer #berrytart',
    postImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKd4kQtnc8bibgiFQ1ZXjj3TyOl3CY8KVHLE1omeX0TfYcDl9GrfnciAQSUdhDrAmcGjeKs6AL6eJmIhj_yLisrjUwnE7l99f1mgdokBELBZBAb6OVClDIi6Rdn7sZRGHuJyJGd7FZmr9GLyLcRpZKzifq5pas_IqieGtyne1GNI8ncxnbL9JpOm0BBoj9XSTGgHZ3qSHrZI0Fg5RlxAuPdVESvmFLP2-DAJBRdkDxlx5rFIe_1Pe_MNcO0UQftaEOsXHmxb2xavjs',
    likesCount: 42,
    commentsCount: 12,
    sharesCount: 5,
    timeAgo: '2h ago',
  },
  {
    id: 'post-2',
    author: MOCK_USERS[1],
    content: '"The dry rub is the key here. Make sure to let it sit for at least 2 hours!"',
    likesCount: 89,
    commentsCount: 24,
    sharesCount: 8,
    timeAgo: '5h ago',
    recipeCard: {
      id: 'recipe-3',
      title: 'Smoked BBQ Ribs',
      imageSrc: MOCK_RECIPES[2].imageSrc,
      rating: 4.9,
      reviewsCount: 245,
      prepTime: '15 mins prep',
      cookTime: '6 hours cook',
    },
  },
  {
    id: 'post-3',
    author: MOCK_USERS[2],
    content: 'La soupe à l\'oignon est prête! Nothing beats this on a cold evening. Recipe link in bio 🧅',
    postImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCSw71LCG4r8d7OSE5aa1NzY15Hj-vBx0hriSCIlmC-H_g1jvN69zejJXYMDqgp12w0GYIIFQcsrbLfEjh4K_RInNHpmPT4zQ66NqH_hcEI8vlQ843_niqPzcLH6HFRDoNbn3RsFD0dm9Ixky0bXfDJhDzzjLpoZuIVaESw-p4wAvdfAdhF1aitMTjRUrQNOD7qkN6VCqldgzzxPZGPmdLNFq-cfSKT_dkpnh4EFWgmX7wg1lX9665Xlt9oMcxQITLR_OswDtr8WGE1',
    likesCount: 134,
    commentsCount: 31,
    sharesCount: 19,
    timeAgo: '1d ago',
  },
];
